### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ghost** [JadedPacks/Magic-Farm-3#1]
- [x] Check configs
- [x] Change over to Jaded mods
- [x] Rewrite MT scripts (Kill JadedBase/JadedTweaks)
- [x] Quality of Life updates
- [x] Make sure it still works :D
